### ISSUE TITLE
Missing mocked method `AsyncStorage.flushGetRequests`

### ISSUE THREAD

**Issue by nmussat** [devmetal/mock-async-storage#10]
This method is used in particular by the Raven (ie. Sentry) client.

https://facebook.github.io/react-native/docs/asyncstorage.html

**Comment by devmetal** [comment]
Thank you for report this :) I will fix this fast as i can :)

**Comment by devmetal** [comment]
Sorry for that delay. I created the method. I think for us enough just an empty function. Because in the real AsyncStorage has more complex implementation and they need this method, i think for mocking, just enough to not throw an exception. But if you had some ideas please feel to free to contribute.

I just created a branch, and i create another one for fix some silly naming stuff in tests and code, after i publish the 2.0.1 version.

**Comment by nmussat** [comment]
Seems perfect to me: I use the same technique in my jest setup file to add an empty method, and everything works as expected.
Thanks for the fix!
